# Generated by Django 2.2.7 on 2019-11-14 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_imagensgaleria_mensagemcoracao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagensgaleria',
            options={'verbose_name': 'Imagem', 'verbose_name_plural': 'Imagens dos eventos'},
        ),
    ]
