# Generated by Django 2.2.7 on 2019-11-15 15:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191114_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('texto', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texto')),
                ('image', models.ImageField(null=True, upload_to='imagemMaterial/', verbose_name='Imagem do Material')),
            ],
            options={
                'verbose_name': 'Material',
            },
        ),
    ]
