# Generated by Django 2.2.7 on 2019-11-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191114_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadMateriais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivoParaDownload', models.FileField(upload_to='arquivoDownload/', verbose_name='Material para download')),
                ('linkParaTeste', models.URLField(max_length=254, null=True, verbose_name='Link para teste')),
            ],
            options={
                'verbose_name': 'Material da semana',
            },
        ),
    ]
