# Generated by Django 2.2.7 on 2019-11-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_downloadmateriais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadmateriais',
            name='linkParaTeste',
            field=models.URLField(blank=True, max_length=254, null=True, verbose_name='Link para teste'),
        ),
    ]
