# Generated by Django 2.2.7 on 2019-11-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='titulo',
            field=models.CharField(default='Campo do Título', max_length=100, verbose_name='Título'),
        ),
    ]
