# Generated by Django 2.2.7 on 2019-11-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191115_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadmateriais',
            name='name',
            field=models.CharField(default='Tópico semanal', max_length=200, verbose_name='Tópico_da_semana'),
        ),
    ]
