# Generated by Django 2.2.7 on 2019-11-15 19:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191115_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='texto',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
