# Generated by Django 2.2.7 on 2019-11-15 21:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_downloadmateriais_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadmateriais',
            name='image',
            field=models.ImageField(null=True, upload_to='imagensMaterial/', verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='downloadmateriais',
            name='texto',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texto'),
        ),
    ]
