# Generated by Django 2.2.7 on 2019-11-15 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191115_1632'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
    ]
