# Generated by Django 2.2.7 on 2019-12-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191115_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.URLField(blank=True, max_length=254, null=True, verbose_name='instagram')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='telefone')),
            ],
            options={
                'verbose_name': 'Informações rodapé',
                'verbose_name_plural': 'Informações rodapé',
            },
        ),
    ]
