# Generated by Django 2.2.7 on 2019-11-15 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_material'),
        ('core', '0005_auto_20191115_1622'),
    ]

    operations = [
    ]
