# Generated by Django 2.2.7 on 2019-12-04 03:36

from django.db import migrations, models
import django_dropbox_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadmateriais',
            name='image',
            field=models.ImageField(null=True, storage=django_dropbox_storage.storage.DropboxStorage(), upload_to='imagensMaterial/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='imagensgaleria',
            name='image',
            field=models.ImageField(null=True, storage=django_dropbox_storage.storage.DropboxStorage(), upload_to='imagensGaleria/', verbose_name='Imagem do evento'),
        ),
        migrations.AlterField(
            model_name='valores',
            name='gif',
            field=models.ImageField(null=True, storage=django_dropbox_storage.storage.DropboxStorage(), upload_to='gifValores/', verbose_name='Gif do valor'),
        ),
        migrations.AlterField(
            model_name='valores',
            name='image',
            field=models.ImageField(null=True, storage=django_dropbox_storage.storage.DropboxStorage(), upload_to='imagemValores/', verbose_name='Imagem do valor'),
        ),
    ]
