# Generated by Django 2.2.7 on 2019-11-15 20:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20191115_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadmateriais',
            name='image',
            field=models.ImageField(null=True, upload_to='imagensMaterial/', verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='downloadmateriais',
            name='texto',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texto'),
        ),
        migrations.AddField(
            model_name='downloadmateriais',
            name='titulo',
            field=models.CharField(default='Titulo', max_length=100, verbose_name='Título'),
        ),
    ]
